bpa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.views import UserProfileDetailView

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bpe_capstone.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^$', 'django.contrib.auth.views.login'),
                       url(r'^login/$', 'django.contrib.auth.views.login'),
                       url(r'^logout/$', 'registration.views.logout'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^info/', include('info.urls', namespace="info")),
                       url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
                       url(r'^query/', include('query.urls', namespace="query")),
                       url(r'^registration/$', 'registration.views.register_user'),
                       url(r'^registration_success/$', 'registration.views.register_success'),
                       url(r'^registration_fail/$', 'registration.views.register_fail'),
                       url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': 'passwordsent/'}, name='password_reset'),
                       url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done',
                           name='password_reset_done'),
                       url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect': 'reset/done/'},
                           name='password_reset_confirm'),
                       url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
                           name='password_reset_complete'),
                       url(r'^stations/', include('stations.urls', namespace="station")),
                       url(r'^profile/$', 'registration.views.user_profile'),

                       url(r"^users/(?P<slug>[\w.@+-]+)/$", UserProfileDetailView.as_view(), name="profile"),

)

query/urls.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Eric Olson, Brady St. John
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#


from django.conf.urls import patterns, url

from query import views

urlpatterns = patterns('',
                       url(r'^$', views.query_index, name='query-index'),
                       url(r'^query-builder/', views.query_builder, name='query-builder'),
                       url(r'^query-result/', views.query_result, name='query-result'),
                       url(r'^status-result/', views.status_result, name='status-result')

)

query/models.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Eric Olson, Brady St. John
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#


from django.db import models

from django.contrib.auth.models import User

import json


# System CPU
class SystemCpu(models.Model):
    # MANY cpus to ONE node
    node     = models.ForeignKey('SystemNode')
    cpu_id   = models.IntegerField(max_length=1024)
    cpu_load = models.FloatField(max_length=1024, default=0)

# System node, that contains information about disk space
class SystemNode(models.Model):
    # MANY nodes to ONE SystemStatus 
    system      = models.ForeignKey('SystemStatus')
    node_id     = models.IntegerField(max_length=100)    
    used        = models.IntegerField(max_length=1024, null=True)
    available   = models.IntegerField(max_length=1024, null=True)

    # calculate and return avg cpu
    def cpuAvg(self):
        total = 0
        num = 0
        for i in self.systemcpu_set.all():
          total += i.cpu_load
          num +=1
        if (num >0):
          return (int(total/num))
        else:
          return 0

    # calculate the color of the CPU box for the HTML page
    def boxColor(self):
        num = self.cpuAvg()
        # 0-25 = success / green color
        if num <25:
          return "success"
        # 26-50 = info  / blue color
        elif num >25 and num <=50:
          return "info"
        # 51-75 = warning / yellow color
        elif num >50 and num <=75:
          return "warning"
        # 75 < = danger/red color
        else:
          return "danger"

    # calculate the diskspace
    def diskSpace(self):
        return self.used/self.available
 

# System Status model holding data for the system, allows for multiple systems
class SystemStatus(models.Model):
    system_id = models.IntegerField(max_length=10)

# Query model holding data from built queries
class Query(models.Model):
    # owner = models.OneToOneField(User)
    owner = models.ForeignKey(User, related_name="owners_query")
    user_name = models.CharField(max_length=24)
    create_date_time = models.DateTimeField('date created')
    query_name = models.CharField(max_length=100)
    start_date_time = models.DateTimeField('query start date time')
    end_date_time = models.DateTimeField('query end date time')
    stations = models.CharField(max_length=1024)
    conditions = models.CharField(max_length=1024)
    file_name = models.CharField(max_length=108, default="n/a")
    status_field = models.CharField(max_length=1024, null=True)

    # QueryResponses
    qr_file = models.CharField(max_length=108, null=True)

    # AnalysisResponses
    ar_file = models.CharField(max_length=108, null=True)

    # Completed
    sr_completed = models.IntegerField(max_length=1024, null=True)

    def set_stations(self, stations):
        """
        Convert list of stations to json object for storage in the model.

        Keyword arguments:
        :param stations:
        :return:
        """
        self.stations = json.dumps(stations)

    def get_stations(self):
        """
        Get the list of stations.

        :return: The list of stations in JSON format.
        """
        return json.loads(self.stations)

    def set_conditions(self, conditions):
        """
        Convert a list of conditions to a JSON object for storage in the model.

        :param conditions: The conditions to convert to JSON.
        :return:
        """
        self.conditions = json.dumps(conditions)

    def get_conditions(self):
        """
        Get the list of conditions as a JSON object.

        :return: The list of conditions in JSON format.
        """
        return json.loads(self.conditions)

query/views.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Eric Olson, Brady St. John, Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.datastructures import MultiValueDictKeyError

from query.forms import QueryForm, StationForm, StationFilterForm, SignalForm, SignalFilterForm
from query.models import Query, SystemStatus, SystemNode, SystemCpu
from stations.models import Station, Signal

import datetime
import time
import json
import socket


class QueryObject:
    """Object used to send a query defined by the user to be processed."""
    def __init__(self, model_id, start_date_time, end_date_time,
                 conditions, file_name, signals):
        self.model_id = model_id
        self.start_date_time = start_date_time
        self.end_date_time = end_date_time
        self.conditions = conditions
        self.file_name = file_name
        self.signals = signals


class SystemStatusObject:
    def __init__(self, system_id):
        self.system_id = system_id


class SystemNodeObject:
    def __init__(self, node_id, used, available):
        self.node_id = node_id
        self.used = used
        self.available = available


class SystemCpuObject:
    def __init__(self, cpu_id, cpu_load):
        self.cpu_id = cpu_id
        self.cpu_load = cpu_load

        
@login_required
def query_index(request):
    """Implementation of the /query/ endpoint."""
    return render(request, 'query/query.html')


@login_required
def query_result(request, pk):
    """Implementation of the /query-result/ endpoint."""
    query = Query.objects.filter(pk=pk)
    context = {'query':query}
    return render(request, 'query/query-result.html', context)


# Display the System Status
@login_required
def status_result(request):
    allqueries = Query.objects.all()
    sys_stat = SystemStatus.objects.all()    
    sys_cpu = SystemCpu.objects.all()
    sys_node = SystemNode.objects.all()
    # Calculate the information for the HTML page
    context = {'sys_stat': sys_stat, 'allqueries': allqueries,
               'sys_cpu': sys_cpu, 'sys_node': sys_node
 }
    return render(request, 'query/status-result.html', context)

# Global variable definitions
current_step = 0                                # The current step in the query builder process
stations = ''                                   # The stations specified by the user
query_model = Query()                           # The model persisted in the database
ss_model = SystemStatus()
query_object = QueryObject(None, None, None,    # The query that is sent to be processed
                           None, None, None)
ss_object = SystemStatusObject(None)
sn_object = SystemNodeObject(None, None, None)
scpu_object = SystemCpuObject(None, None)


# calculate and return a results page render
# - pass in a request and query model,
# - and return the rendered page 
@login_required
def return_result_page(request, query_model):
    query = Query.objects.filter(pk=query_model.pk)
    context = {'query':query}
    return render(request, 'query/query-result.html', context)


def get_context(username, form, station_form, station_filter_form, signal_form,
                signal_filter_form, step):
    """Create a context to send to the front-end with the given parameters."""
    return {'username': username, 'form': form, 'station_form': station_form,
            'station_filter_form': station_filter_form, 'signal_form': signal_form,
            'signal_filter_form': signal_filter_form, 'current_step': step}


# Builds a query given user input
@login_required
def query_builder(request):
    """Implementation of the /query-builder/ endpoint."""

    # Global variables
    global query_model      # The model persisted in the database
    global query_object     # The query that is sent to be processed
    global current_step     # Current step in the builder
    global stations         # The stations selected by the user

    # Ensure the user has rights to the page and save their information:
    username = None
    if request.user.is_authenticated():
        username = request.user.username
        query_model.user_name = username
        creation_date = time.strftime("%Y-%m-%d %H:%M:%S")
        query_model.create_date_time = creation_date

    # Instantiate blank form objects:
    if request.method == 'GET':
        detail_form = QueryForm()
        station_form = StationForm()
        station_filter_form = StationFilterForm(initial=StationFilterForm.get_initial_station_values())
        signal_form = SignalForm()
        signal_filter_form = SignalFilterForm(initial=SignalFilterForm.get_initial_signal_values())

        context = get_context(username, detail_form, station_form, station_filter_form, signal_form,
                              signal_filter_form, current_step)
        return render(request, 'query/query-builder.html', context)

    # Request method is POST: Create and handle the forms with the given user input:
    detail_form = QueryForm(request.POST, request.FILES)
    signal_form = SignalForm(request.POST)
    signal_filter_form = SignalFilterForm(request.POST,
                                          initial=SignalFilterForm.get_initial_signal_values())
    station_form = StationForm(request.POST)
    station_filter_form = StationFilterForm(request.POST,
                                            initial=StationFilterForm.get_initial_station_values())
    # Save the first form data if the first form is valid and the user clicked 'next':
    if detail_form.is_valid() and 'save-details' in request.POST:
        # Re-make the signal_form object:
        signal_form = SignalForm()

        # Go to the next step in the process since the form submission was a success:
        current_step = 1

        # Retrieve user input from the front end and place it in the Query model:
        query_model.owner = request.user
        query_model.query_name = detail_form.cleaned_data['query_name']
        start_date = detail_form.cleaned_data['start_date']
        start_time = detail_form.cleaned_data['start_time']
        start_date_time = datetime.datetime.combine(start_date, start_time)
        query_model.start_date_time = start_date_time
        end_date = detail_form.cleaned_data['end_date']
        end_time = detail_form.cleaned_data['end_time']
        end_date_time = datetime.datetime.combine(end_date, end_time)
        query_model.end_date_time = end_date_time

        try:
            file = request.FILES["file"]
            file_name = file.name
        except MultiValueDictKeyError:
            file_name = ""
        query_model.file_name = file_name

        # Instantiate the query object that will be sent to be processed:
        query_object = QueryObject(None, start_date_time, end_date_time,
                                   None, file_name, None)

        context = get_context(username, detail_form, station_form, station_filter_form, signal_form,
                              signal_filter_form, current_step)
        return render(request, 'query/query-builder.html', context)
    elif not detail_form.is_valid() and 'save-details' in request.POST:
        signal_form = SignalForm()
        current_step = 0
        context = get_context(username, detail_form, station_form, station_filter_form, signal_form,
                              signal_filter_form, current_step)
        return render(request, 'query/query-builder.html', context)
    elif 'save-details' in request.POST:
        signal_form = SignalForm()
        current_step = 1
        context = get_context(username, detail_form, station_form, station_filter_form, signal_form,
                              signal_filter_form, current_step)
        return render(request, 'query/query-builder.html', context)
    elif station_filter_form.is_valid() and 'station-filter-submit' in request.POST:
        detail_form = QueryForm()
        signal_form = SignalForm()
        current_step = 1

        station_voltage = request.POST.getlist('station_voltage')
        pmu_channel = request.POST.getlist('pmu_channel')
        StationForm.update_stations(station_form, station_voltage, pmu_channel)
        station_form = StationForm()

        context = get_context(username, detail_form, station_form, station_filter_form, signal_form,
                              signal_filter_form, current_step)
        return render(request, 'query/query-builder.html', context)
    elif 'station-filter-submit' in request.POST:
        detail_form = QueryForm()
        signal_form = SignalForm()
        current_step = 1

        context = get_context(username, detail_form, station_form, station_filter_form, signal_form,
                              signal_filter_form, current_step)
        return render(request, 'query/query-builder.html', context)
    elif station_form.is_valid() and 'station-submit' in request.POST:
        detail_form = QueryForm()
        current_step = 2

        # Retrieve the list of stations the user specified and update the signal form with those stations:
        stations = request.POST.getlist('stations')
        query_model.set_stations(stations)
        station_objects = get_stations(stations)

query/templates/query/query-builder.html
<!--
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Brady St. John
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#
-->
{% extends "user/base.html" %}

{% block title %}Query Builder{% endblock %}


{% block header %}
{% block header-title %}
      Query Builder
{% endblock %}
{% endblock %}



{% load staticfiles %}

{% block content %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="{% static '/static/general/queryBuilder.css' %}"/>
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        var sendQueryError = $('#send-query-error');
        var signalFormWrapper = $('#signal-form-wrapper');

        $('.fieldSet').each(function(index) {
            if (index == {{ current_step }}) {
                return true;
            }
            $('#' + this.id).hide();
        });

        $('.nextStep').bind('click', function(){
            var currentId = parseInt(this.id.replace('next-step-', ''));
            var fieldSetId = '#field-set-' + currentId;
            $(fieldSetId).hide();
            var nextId = currentId + 1;
            var nextFieldSetId = '#field-set-' + nextId;
            $(nextFieldSetId).show();
        });

        $('.previousStep').bind('click', function() {
            var currentId = parseInt(this.id.replace('previous-step-', ''));
            var fieldSetId = '#field-set-' + currentId;
            $(fieldSetId).hide();
            var previousId = currentId - 1;
            var previousFieldSetId = '#field-set-' + previousId;
            $(previousFieldSetId).show();
        });
                      
                      
                      
        $('#select-all-stations').bind('click', function() {
             var stations = $('#id_stations option');
             if (stations.prop('selected') == true) {
             stations.prop('selected', false);
             return;
             }
             
             stations.prop('selected', true);
        });

        $('#select-all-signals').bind('click', function() {
            var signals = $('#id_signals option');
            if (signals.prop('selected') == true) {
                signals.prop('selected', false);
                return;
            }

            signals.prop('selected', true);
        });
    });


    $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: '1900:' + new Date().getFullYear(),
      showOn: 'button'
    }).next('button').text('').button({
            icons: {
                primary: 'icon-calendar'
            },
            text: false
        });
    });
</script>

<form action="/query/query-builder/" method="post" enctype=multipart/form-data class="form-inline">
    {% csrf_token %}

    <h3>Complete 5 steps to send a query:</h3>
    {{ form.non_field_errors }}
    <fieldset id="field-set-1" class="fieldSet form-group">
        <h3>1. Fill Out Query Details</h3>
        <div class="fieldWrapper">
            <p>
                {{ form.query_name.errors }}
                <label for="{{ form.query_name.id_for_label }}">Name of Your Query: </label>
                {{ form.query_name }}
            </p>
        </div>


        <div class="fieldWrapper">
            <table width="80%">
                <tr>
                    <td>{{ form.start_date.errors }}</td>
                    <td>{{ form.start_time.errors }}</td>
                </tr>
                <tr>
                    <td>
                        <label for="{{ form.start_date.id_for_label }}">Start Date: </label>
                        {{ form.start_date }}
                    </td>
                    <td>
                        <label for="{{ form.start_time.id_for_label }}">Start Time: </label>
                        {{ form.start_time }}
                    </td>
                </tr>
            </table>
        </div>

        <div class="fieldWrapper">
            <table width="80%">
                <tr>
                    <td>{{ form.end_date.errors }}</td>
                    <td>{{ form.end_time.errors }}</td>
                </tr>
                <tr>
                    <td>
                        <label for="{{ form.end_date.id_for_label }}">End Date: </label>
                        {{ form.end_date }}
                    </td>
                    <td>
                        <label for="{{ form.end_time.id_for_label }}">End Time: </label>
                        {{ form.end_time }}
                    </td>
                </tr>
            </table>
        </div>

        <div class="fieldWrapper">
            <table width="80%">
                <tr>
                    <td> {{ form.file.errors }} </td>
                </tr>
                <tr>
                    <td>
                        <label for="{{ form.file.id_for_label }}">Analysis File (Optional): </label> 
                        {{ form.file }}
                    </td>
                </tr>
            </table>
        </div>
        <button id="next-step-1" class="btn btn-primary nextStep" type="submit" name="save-details">Next Step</button>
    </fieldset>

    <fieldset id="field-set-2" class="fieldSet">
        <h3>2. Filter the List of Stations (Optional)</h3>
        <div class="fieldWrapper">
            <table width="80%" class="choiceTable">
                <tr>
                    <td><label for="{{ station_filter_form.station_voltage.id_for_label">Voltage</label></td>
                    <td><label for="{{ station_filter_form.pmu_channel.id_for_label">Channel</label></td>
                </tr>
                <tr>
                    <td>{{ station_filter_form.station_voltage }}</td>
                    <td>{{ station_filter_form.pmu_channel }}</td>
                </tr>
            </table>
        </div>
        
        <p><small>*Leaving all boxes in a field unchecked is the same as selecting them all.</small></p>

        <button id="refresh-stations" class="btn btn-primary nextStep" type="submit" name="station-filter-submit">Refresh Stations</button>

        <h3>3. Select Stations to Filter On (Optional)</h3>
        <div class="fieldWrapper">
            {{ station_form.errors }}
            <!--<p><label for="{{ form.stations.id_for_label }}"><b>Select Stations</b> (Optional)</label></p>-->
            {{ station_form }}
            <br>
            <button id="select-all-stations" class="btn btn-default btn-sm" type="button"> Toggle All</button>
            <small> (CTRL + Click or SHIFT + Click to select multiple)</small>
        </div>

        <button id="previous-step-2" class="btn btn-default previousStep" type="button">Previous Step</button>
        <button id="next-step-2" class="btn btn-primary nextStep" type="submit" name="station-submit">Next Step</button>
        <!--<button id="next-step-3" class="btn btn-primary nextStep" type="submit">Next Step</button>-->
    </fieldset>

    <fieldset id="field-set-3" class="fieldSet">
        <h3>4. Filter the List of Signals (Optional)</h3>

        <div class="fieldWrapper">
            <table class="choiceTable">
                <tr>
                    <td><label for="{{ signal_filter_form.signal_voltage.id_for_label">Voltage</label></td>
                    <td><label for="{{ signal_filter_form.signal_type.id_for_label">Type</label></td>
                    <td><label for="{{ signal_filter_form.signal_asset.id_for_label">Asset</label></td>
                    <td><label for="{{ signal_filter_form.signal_unit.id_for_label">Unit</label></td>
                    <td><label for="{{ signal_filter_form.signal_phase.id_for_label">Phase</label></td>
                </tr>
                <tr>
                    <td>{{ signal_filter_form.signal_voltage }}</td>
                    <td>{{ signal_filter_form.signal_type }}</td>
                    <td>{{ signal_filter_form.signal_asset }}</td>
                    <td>{{ signal_filter_form.signal_unit }}</td>
                    <td>{{ signal_filter_form.signal_phase }}</td>
                </tr>
            </table>
        </div>
        
        <p><small>*Leaving all boxes in a field unchecked is the same as selecting them all.</small></p>

        <!-- <input class="button" type="reset" value="Reset"/> -->
        <!--<input class="button" type="submit" style="width: 120px;" value="Get Signals" id="refresh-signals" name="refresh"/>-->
        <button id="refresh-signals" class="btn btn-primary nextStep" type="submit" name="signal-filter-submit">Refresh Signals</button>
            <!--<button id="next-step-3" class="btn btn-primary nextStep" type="submit">Next Step</button>-->

        <h3>5. Select Signals</h3>

        {{ signal_form.non_form_errors }}
        <div class="fieldWrapper" id="signal-form-wrapper">
            <!--<br><label for="{{ signal_form.signals.id_for_label }}"><b>List of Signals</b></label>-->
            {{ signal_form.signals.errors }}
            {{ signal_form.signals }}
            <p><button id="select-all-signals" class="btn btn-default btn-sm" type="button"> Toggle All</button></p>
            <small> (CTRL + Click or SHIFT + Click to select multiple)</small>

        </div>
        <button id="previous-step-3" class="btn btn-default previousStep" type="button">Previous Step</button>
        <input  id="send-query" class="btn btn-success" type="submit" value="Send Query" name="send"/>
    </fieldset>
</form>

<br><br>
<a href="/logout">Logout</a>
{% endblock %}

query/templates/query/query-result.html
<!--
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Eric Olson, Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#
-->

{% extends "user/base.html" %}

{% block title %}Job Results{% endblock %}

{% block header %}
  {% for q in query %}
    {% block header-title %}
          {{q.query_name}}, #{{q.pk}}
    {% endblock %}
  {% endfor %}
{% endblock %}


{% block content %}
{% for q in query %}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Query Information</h3>
  </div>
  <div class="panel-body">
    <ul>
      <li>Username: {{q.user_name}}</li>
      <li>Query Name:{{q.query_name}}</li>
      <li>Filename: {{q.file_name}}</li>
      <li>Created: {{q.create_date_time}}</li>
      <li>Start: {{q.start_date_time}}</li>
      <li>End: {{q.end_date_time}}</li>          
    </ul>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Job Response</h3>
  </div>
  <div class="panel-body">
    <ul>
      <LI>File: <u>{{q.qr_file}}</u></LI>
    </ul>
  </div>      
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Analysis Response</h3>
  </div>
  <div class="panel-body">
    <ul>
      <LI>File: <u>{{q.ar_file}}</u></LI>
    </ul>
  </div>      
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Status Response</h3>
  </div>
  <div class="panel-body">
    <ul>
      <LI>Completed: <u>{{q.sr_completed}}</u></LI>
      <div class="progress">
        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{sr_completed}}" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: {{q.sr_completed}}%;">
          {{q.sr_completed}}%
        </div>
      </div>
      <LI>Status Report: "{{q.status_field}}"</LI>
    </ul>
  </div>      
</div>



{% endfor %}
{% endblock %}

query/templates/query/query.html
<!--
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Brady St. John
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#
-->
{% extends "user/base.html" %}

{% block title %}Query Index{% endblock %}


{% block header %}
{% block header-title %}
      Query Index
{% endblock %}
{% endblock %}





{% block content %}
<div>
    <ul>
        <li><a href="/query/query-builder/">Build a new Query</a></li>
    </ul>
</div>
{% endblock %}