bpa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.views import UserProfileDetailView

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'bpe_capstone.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^$', 'django.contrib.auth.views.login'),
                       url(r'^login/$', 'django.contrib.auth.views.login'),
                       url(r'^logout/$', 'registration.views.logout'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^info/', include('info.urls', namespace="info")),
                       url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
                       url(r'^query/', include('query.urls', namespace="query")),
                       url(r'^registration/$', 'registration.views.register_user'),
                       url(r'^registration_success/$', 'registration.views.register_success'),
                       url(r'^registration_fail/$', 'registration.views.register_fail'),
                       url(r'^resetpassword/$', 'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': 'passwordsent/'}, name='password_reset'),
                       url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done',
                           name='password_reset_done'),
                       url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
                           'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect': 'reset/done/'},
                           name='password_reset_confirm'),
                       url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete',
                           name='password_reset_complete'),
                       url(r'^stations/', include('stations.urls', namespace="station")),
                       url(r'^profile/$', 'registration.views.user_profile'),

                       url(r"^users/(?P<slug>[\w.@+-]+)/$", UserProfileDetailView.as_view(), name="profile"),

)

dashboard/urls.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#


from django.conf.urls import patterns, url

from dashboard import views

urlpatterns = patterns('',
                       url(r'^$', views.dashboard, name='dashboard'),
                       url(r'^delete_query/(?P<pk>\d+)/$', views.delete_query, name='delete_query'),
)

query/urls.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Eric Olson, Brady St. John
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#


from django.conf.urls import patterns, url

from query import views

urlpatterns = patterns('',
                       url(r'^$', views.query_index, name='query-index'),
                       url(r'^query-builder/', views.query_builder, name='query-builder'),
                       url(r'^query-result/', views.query_result, name='query-result'),
                       url(r'^status-result/', views.status_result, name='status-result')

)

dashboard/models.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#

from django.db import models
from django.contrib.auth.models import User


class Dashboard(models.Model):
    owner = models.ForeignKey(User)

dashboard/views.py
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#

from django.shortcuts import render
from query.models import Query
from django.contrib.auth.decorators import login_required


@login_required
def dashboard(request):
    username = None
    if request.user.is_authenticated():
        username = request.user.username
    allqueries = Query.objects.all()
    myqueries = Query.objects.filter(user_name = username)
    context = {'username': username, 'allqueries':allqueries, 'myqueries':myqueries}
    return render(request, 'dashboard/dashboard.html', context)


@login_required
def delete_query(request, pk):
    Query.objects.filter(pk=pk).delete()
    username = None
    if request.user.is_authenticated():
        username = request.user.username
    allqueries = Query.objects.all()
    myqueries = Query.objects.filter(user_name = username)
    context = {'username': username, 'allqueries':allqueries, 'myqueries':myqueries}
    return render(request, 'dashboard/dashboard.html', context)

dashboard/templates/dashboard/dashboard.html
<!--
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Garrison Jenson, Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#
-->

{% extends "user/base.html" %}

{% load staticfiles %}

{% block title %}Dashboard{% endblock %}

{% block header %}
{% block header-title %}
      Dashboard
{% endblock %}
{% endblock %}



{% block content %}

<div class="container-fluid">
  <div class="row">
      
    <!-- display all queries -->  
    <div class="col-xs-3">
      <h4> All Jobs </h4>
        <ul class="list-group">
          {% for q in allqueries %}
            <li class="list-group-item">
              <a class="btn btn-link" href="{% url 'query:query-result' pk=q.pk %}">{{ q.query_name }}</a>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 0em; width: {{q.sr_completed}}%;">
                        {{q.sr_completed}}%
                  </div>
                </div>
            </li>
          {% endfor %}
        </ul>
    </div>

    <!-- display my queries, with delete option-->  
    <div class="col-xs-3">
      <h4> My Jobs </h4>
        <ul class="list-group">
          {% for q in myqueries %}
            <li class="list-group-item">
              <a class="btn btn-link" href="{% url 'query:query-result' pk=q.pk %}">{{ q.query_name }}</a>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 0em; width: {{q.sr_completed}}%;">
                        {{q.sr_completed}}%
                  </div>
                </div>
                <a class="btn btn-link" href="{% url 'dashboard:delete_query' pk=q.pk %}" role="button">delete job</a>
            </li>
          {% endfor %}
        </ul>
    </div> 
      
  </div>
</div>
<!-- display link to profile information -->
<a href="{% url 'profile' slug=user.username %}"><b>{{ user.username }} 's Profile</b></a>
{% endblock %}

dashboard/templates/dashboard/results.html
<!--
# Bonneville Power Adminstration Front-End
# Copyright (C) 2015  Garrison Jenson, Matei Mitaru
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, US$
#
-->

{% extends "user/base.html" %}

{% load staticfiles %}

{% block title %}Results{% endblock %}

{% block header %}
{% block header-title %}Welcome, {{ username }}!{% endblock %}
{% endblock %}

{% block content %}
<p>
    Hello. This is the results page. It is currently under construction.
</p>





<a href="/logout">Logout</a>
{% endblock %}